### ISSUE TITLE
예상 독자 조사

### ISSUE THREAD

**Issue by longfin** [planetarium/ninechronicles-devforum#2]

**Comment by U-lis** [comment]
예상 독자까지는 아니지만 community 에서는 어떤걸 원하는지 cue 를 얻기 위해 [여기](https://www.notion.so/planetarium/Lately-asked-question-suggestions-14d68eb33e8f42bca665a596e9e4204d)에다가 디코에는 어떤 질문/요청이 들어오는지 7, 8월의 디코 기록을 보며 정리하고 있습니다.

**Comment by longfin** [comment]
- 가장 쉽게 예상할 수 있는 독자는 **9c EDT**(Ecosystem Development Team)입니다. 
- 그 다음으로는 Osama와 같은 커뮤니티에서 이미 **활동 중인 모드 개발자**들로 생각해볼 수 있습니다.
- 조금 까다로울 수 있지만, 잠재적인 고객으로는 나인 크로니클에 대해 리뷰 해보고 싶은 파트너사나 개발자들을 생각해 볼 수 있는데
  - 지속적인 피드백을 얻을 수 있으면 좋지만, 파트너사는 이미 다른 목적(i.e., 적용 가능성)으로 검토를 하고 있는 것으로 예상되어 좋은 피드백을 받을 수 있을지 의문이긴 합니다.

현실적인 이유로 EDT나 모드 개발자를 우선 타깃하는게 좋을 것 같고, 그들이 이미 관심을 보인 주제들에 대해 시놉시스를 구성하는 것이 구체적으로 보입니다.
