### ISSUE TITLE
The Preload Process

### ISSUE THREAD

**Issue by longfin** [planetarium/ninechronicles-devforum#20]
Original text: https://www.notion.so/planetarium/Preload-acb889cfed824350b6986867c4e73172

**Comment by Akamig** [comment]
Translate Completed.
https://forumwiki.planetarium.dev/w/index.php/Preload_Procedure
https://forumwiki.planetarium.dev/w/index.php?title=Preload_Procedure&type=revision&diff=57&oldid=56

**Comment by BasixKOR** [comment]
https://devforum.nine-chronicles.com/t/launcher-preload-procedure/30/2
