### ISSUE TITLE
Explaining Application Protocol Versions

### ISSUE THREAD

**Issue by longfin** [planetarium/ninechronicles-devforum#23]

**Comment by moreal** [comment]
You wanted to say `App Protocol Version`, right? (It's same meaning)

**Comment by moreal** [comment]
I wrote the topic about this issue.

https://devforum.nine-chronicles.com/t/explain-app-protocol-version-a-k-a-apv/34

**Comment by Akamig** [comment]
https://devforum.nine-chronicles.com/t/explain-app-protocol-version-a-k-a-apv/34
