### ISSUE TITLE
튜토리얼 해볼 만한 시나리오

### ISSUE THREAD

**Issue by longfin** [planetarium/ninechronicles-devforum#3]

**Comment by U-lis** [comment]
1. 9c-launcher 를 받아서 tutorial 을 따라 launcher 를 켜본다. (현재 설정파일로는 mainnet)
    -  이거로 게임이 잘 되는 것을 확인한다.
    -  오 소스빌드로 게임이 되는군! 이제 건드려볼 수 있겠다.
2.  어디를 손볼까?
    - launcher 를 보자 -> launcher modification 문서 안내
    - Headless 를 보자 -> Headless getting stared 문서 안내
    - NineChronicles 를 보자 -> NineChronicles getting started 문서 안내
    - mod 나 addon 같은걸 만들고 싶은데? -> Libplanet? GQL? 문서 안내
    - 기타 어떤 (편의)기능이 있으면 좋을지에 대해서는 굳이 개발자가 아니라도 community 에서 물어보고 많이 손드는 쪽은 길을 열어주는 식으로? 
    - 이런걸 사람들이 원한다! 원기옥을 모아줘! 식의 참여 유도...?

**Comment by longfin** [comment]
> 기타 어떤 (편의)기능이 있으면 좋을지에 대해서는 굳이 개발자가 아니라도 community 에서 물어보고 많이 손드는 쪽은 길을 열어주는 식으로?
> 이런걸 사람들이 원한다! 원기옥을 모아줘! 식의 참여 유도...?

요거 시나리오 추출하는건 EDT 에서 하고 있는 활동들이 어떤게 있는지 보고 저도 의견 남기겠습니다.

**Comment by U-lis** [comment]
community 에서는 어떤걸 원하는지 cue 를 얻기 위해 [여기](https://www.notion.so/planetarium/Lately-asked-question-suggestions-14d68eb33e8f42bca665a596e9e4204d
)에다가 디코에는 어떤 질문/요청이 들어오는지 7, 8월의 디코 기록을 보며 정리하고 있습니다.

**Comment by U-lis** [comment]
직접 addon(?) 을 하나 만들어보면 어디부터 보면 좋고 어디가 부족한지 알 수 있지 않을까 싶어 여기저기 둘러보고 있습니다.
이런 부분들이 개발자 포털을 구성는데 도움이 될 수 있지 않을까 해서요.
다만 이건 가설에 불과하고 제가 만들고자 하는 것에 국한될 수 있어서 본격 진행 여부는 합의를 거치고자 합니다.

**Comment by U-lis** [comment]
https://github.com/U-lis/9c-status-monitor
에서 GQL 등을 이용해 내 캐릭터의 상태를 확인하는 것을 만들어보고 있습니다.
개발 과정에 대한 note는 notion 에 별도로 작업 예정입니다.
대강 이번주 화~수 정도 완성하고 일지를 작성하는 것을 목표로 하고 있습니다.

**Comment by longfin** [comment]
스프린트 2 종료까지 1~2개 정도 시나리오(e.g., https://github.com/planetarium/ninechronicles-developer-portal/issues/3#issuecomment-1206031588, FioX가 만들던 RPC노드 측정기)를 이 저장소에 markdown 포맷으로 적당히 올려봅니다.

**Comment by U-lis** [comment]
https://github.com/tx0x/chrono
@BasixKOR  님이 알려주신 것 추가합니다. MetaMask 같은 9c 지갑 chrome extension 입니다.

**Comment by longfin** [comment]
https://planetariumhq.slack.com/archives/C01C4NG2H9S/p1660301867678229?thread_ts=1660278260.080579&cid=C01C4NG2H9S

> Of course.
They are as private as they contain moderation data or credentials so we have them closed up for security purposes.
This is NCGM which handles all the data gathering:
https://github.com/FioX0/DiscordBotPrivate
This is our Ranking Puller:
https://github.com/FioX0/LeaderboardsNCGM
TicketBot:
https://github.com/FioX0/TicketBot
The current node the EDT is using is:
https://github.com/FioX0/NineChronicles.Headless/tree/nodev260
Which is base v260 + Arena GQL Fix + GQL Replay query.
Which got docker image on:
fiox/9c-node:v260
