### ISSUE TITLE
Revisit category structure

### ISSUE THREAD

**Issue by longfin** [planetarium/ninechronicles-devforum#58]
[Previous idea](https://www.notion.so/planetarium/9c-forum-category-ef7671856a75416386b52275b830ed60#87d11028225040f999d5b4bd82ee4df9)

**Comment by U-lis** [comment]
현재 devforum 에 작성되어 있는 글을 모아서 (이전 category 구조 제안을 기초로) 어떤 구조로 category 를 rebuild 할 수 있을 지 확인한다.
 - [x] 현재 글을 기반으로 상태 조망 + 현재 tag 수집
 - [x] 새로운 category 구조 제안
 - [x] Tag 정리
