### ISSUE TITLE
Play Nine Chronicles with GraphQL API

### ISSUE THREAD

**Issue by moreal** [planetarium/ninechronicles-devforum#6]
- Examples
  - [x] #43

**Comment by BasixKOR** [comment]
I think this shares similar concerns with #5, can we merge the former into this?

**Comment by moreal** [comment]
Sorry for late reply 😭 Yes, I think we can.

**Comment by moreal** [comment]
I will write an article for `stake` and `claim_stake_reward` actions with `planetarium/lib9c-wasm`.
