### ISSUE TITLE
Sphere: Easy interaction with Libplanet-based blockchains using JavaScript

### ISSUE THREAD

**Issue by BasixKOR** [planetarium/ninechronicles-devforum#63]

**Comment by longfin** [comment]
@U-lis  Please review [this article](https://devforum.nine-chronicles.com/t/sphere-easy-interaction-with-libplanet-based-blockchains-using-javascript/102) 🙏

**Comment by longfin** [comment]
@Akamig Could you apply [the feedback](https://devforum.nine-chronicles.com/t/sphere-easy-interaction-with-libplanet-based-blockchains-using-javascript/102/2)?

**Comment by U-lis** [comment]
Sphere 문서에 있는 API 중 일부가 회사 컴에서 개발중인 상태 (push 안됨)
이걸 완성하는 것이 필요하다. from @BasixKOR  to @Akamig

**Comment by Akamig** [comment]
Applying feedback complete. I will handle Implementing additional sphere API on a separate issue.
